### PR TITLE
Models/schemas

### PR DESCRIPTION
**Pull request by killeen31**
updates to backend

### CODE REVIEW

**Review by MoxUFO — CHANGES_REQUESTED** [review]
i do believe we are redeisgning our database so we should hold off on the changes

**Review by oreynosa12 — DISMISSED** [review]
Nice!

**Review by oreynosa12 — CHANGES_REQUESTED** [review]
I think this one is correct as it was already using camel case

**Review by oreynosa12 — APPROVED** [review]
Approved!

**Pull request closed without merging**
